### ISSUE TITLE
open file crashed

### ISSUE THREAD

**Issue by tjumsl** [verylowfreq/solvespace#6]
Dear Sir,

I try to open file using the online solvespace version, but it crashed, any reason what is wrong?

**Comment by verylowfreq** [comment]
@tjumsl Thanks :smile:

This is bacause uploaded binaries (I uploaded to GitHub Pages) are incorrect. I made mistake branch switching on git in sourcecode repository.

I fixed it and this should be works;
https://verylowfreq.github.io/experimental-solvespace-on-browser/bin-2022080802/solvespace.html

Please try it !

Additional note:
If you encountered extrude operation often fails, please check "configuration -> chord torelance" value. If it is 0, set 0.1 .
Users who opened old builds may encounter this issue. This is fixed the latest (2022080802) build.

**Comment by tjumsl** [comment]
What is the supported file format? I tried several step file, all prompted file corrupt...

**Comment by verylowfreq** [comment]
Supported file format is same as SolveSpace on the Desktop native application (Windows, macOS, or Linux).

Opening STEP file is not supported. Only exporting is supported (but not tested on browser build).
SolveSpace can open ".slvs" file (SolveSpace-specific format).

If you are not familier with SolveSpace, please try on desktop.

This is the bug that file dialog accepts STEP file when you open with File->Open menu.  In this situation, file dialog should only accept ".slvs" file but not implemented in this build.

Regards.
